# Generated by Django 5.2.4 on 2025-07-13 05:34

import maintenance.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[maintenance.validators.validate_vin]),
        ),
    ]
